bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
bgp_peer_groups:
  EVPN_OVERLAY_PEERS:
    password: null
  IPv4_UNDERLAY_PEERS:
    password: null
  MLAG_IPv4_UNDERLAY_PEER:
    password: null
fabric_name: AVD-Demo
l2leaf:
  defaults:
    platform: vEOS
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    DC1_L2LEAF1:
      filter:
        tags:
        - opzone
        - web
        - app
        tenants:
        - Tenant_A
      nodes:
        DC1-L2LEAF1A:
          id: 8
          l3leaf_interfaces:
          - Ethernet7
          - Ethernet7
          mgmt_ip: 192.168.200.112/24
      parent_l3leafs:
      - DC1-LEAF2A
      - DC1-LEAF2B
      platform: 750XP
      uplink_interfaces:
      - Ethernet1
      - Ethernet2
    DC1_L2LEAF2:
      filter:
        tags: []
        tenants: []
      mlag_interfaces:
      - Ethernet3
      - Ethernet4
      nodes:
        DC1-L2LEAF2A:
          id: 9
          l3leaf_interfaces:
          - Ethernet7
          - Ethernet7
          mgmt_ip: 192.168.200.113/24
        DC1-L2LEAF2B:
          id: 10
          l3leaf_interfaces:
          - Ethernet8
          - Ethernet8
          mgmt_ip: 192.168.200.114/24
      parent_l3leafs:
      - DC1-SVC3A
      - DC1-SVC3B
      platform: 720XP
      uplink_interfaces:
      - Ethernet1
      - Ethernet2
l3leaf:
  defaults:
    mlag_interfaces:
    - Ethernet3
    platform: vEOS
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    spines:
    - DC1-SPINE1
    - DC1-SPINE2
    uplink_to_spine_interfaces:
    - Ethernet1
    - Ethernet2
    virtual_router_mac_address: 00:dc:00:00:00:0a
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tags:
        - web
        - app
        tenants:
        - all
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.200.105/24
          spine_interfaces:
          - Ethernet1
          - Ethernet1
      platform: '7160.0'
    DC1_LEAF2:
      bgp_as: 65102
      filter:
        tags:
        - opzone
        - web
        - app
        - db
        tenants:
        - Tenant_A
        - Tenant_B
        - Tenant_C
      mlag_interfaces:
      - Ethernet45
      - Ethernet46
      nodes:
        DC1-LEAF2A:
          id: 2
          mgmt_ip: 192.168.200.106/24
          spine_interfaces:
          - Ethernet2
          - Ethernet2
        DC1-LEAF2B:
          id: 3
          mgmt_ip: 192.168.200.107/24
          spine_interfaces:
          - Ethernet3
          - Ethernet3
      platform: 7050SX
    DC1_SVC3:
      bgp_as: 65103
      filter:
        tags:
        - opzone
        - web
        - app
        - db
        tenants:
        - Tenant_A
        - Tenant_B
        - Tenant_C
      nodes:
        DC1-SVC3A:
          id: 4
          mgmt_ip: 192.168.200.108/24
          spine_interfaces:
          - Ethernet4
          - Ethernet4
          - Ethernet4
          - Ethernet4
        DC1-SVC3B:
          id: 5
          mgmt_ip: 192.168.200.109/24
          spine_interfaces:
          - Ethernet5
          - Ethernet5
          - Ethernet5
          - Ethernet5
      platform: 7280R
leaf_bgp_defaults:
- update wait-install
- distance bgp 20 200 200
- no bgp default ipv4-unicast
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24
overlay_loopback_network_summary: 192.168.255.0/24
p2p_uplinks_mtu: 1500
spine:
  bgp_as: 65100
  leaf_as_range: 65101-65132
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 192.168.200.101/24
    DC1-SPINE2:
      id: 2
      mgmt_ip: 192.168.200.102/24
  platform: 7280R3
spine_bgp_defaults:
- update wait-for-convergence
- update wait-install
- distance bgp 20 200 200
- no bgp default ipv4-unicast
underlay_p2p_network_summary: 172.31.255.0/24
vtep_loopback_network_summary: 192.168.254.0/24
vxlan_vlan_aware_bundles: 1
