---
- name: Build Switch configuration
  hosts: AVD-Demo
  connection: local
  gather_facts: no
  tasks:
    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_l3ls_evpn
    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP
  connection: local
  gather_facts: no
  tasks:
    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'AVD-Demo'
        configlets_prefix: 'avd'
        device_filter: 'avd'
        state: present
